### ISSUE TITLE
how to delete e.dragElem ?

### ISSUE THREAD

**Issue by sayanbrainium** [peterh32/react-drag-drop-container#10]
Hi I would like to delete the dropped item in drop are using e.dragElem or empty drop area , how can I do that?

**Comment by peterh32** [comment]
See here https://github.com/peterh32/react-drag-drop-container/blob/master/demo/DragFoodToAnimalsDemo.jsx#L22  -- after a successful drop it does
```e.sourceElem.style.visibility="hidden";```
You could do the same thing only you'd set `display='none'` or delete the thing altogether.

**Comment by peterh32** [comment]
I hope that answered your question. If not then re-open this or create a new issue.
