### ISSUE TITLE
 I need to pass my own styles

### ISSUE THREAD

**Issue by agustinramos** [peterh32/react-drag-drop-container#13]
I need to pass my own styles to 
DragDropContainer
DropTarget

**Comment by agustinramos** [comment]
add ...
    <div style={{...styles, ...this.props.style}}} ref={(container) => { this.containerElem = container; }}>
        {this.setDraggableFalseOnChildren()}
        {ghost}
    </div>

**Comment by peterh32** [comment]
I really don't think this is an issue -- you can style the code around it or style the contents. If you have a specific need please explain further but in the meantime I am closing this.
