### ISSUE TITLE
dragged element hidden if wrapper has overflow:auto in css

### ISSUE THREAD

**Issue by repunck** [peterh32/react-drag-drop-container#14]
I receive a list to drag from, but sometimes the list is 2 screens high, so I made a containing div with an overflow:auto. The problem is that when I do that, even if I change the zIndex value of the DragDropContainer to 10 millions, it still disappears when it passes over the scrollbar. Is there some way to fix that?

P.S. I've already tried it on your demo page, I've set the food class to have an overflow:auto, and the food icons disappear when they get out of their containing div. HELP please.

**Comment by peterh32** [comment]
Ugh. You are right. This will require changing the dragged element from position: relative to position: fixed or possibly absolute. Hmmm.

**Comment by peterh32** [comment]
This should be fixed in release 5.0.0!
