### ISSUE TITLE
Warning: setState(...): is shown after clicking on the DragDropContainer and closing modal window.

### ISSUE THREAD

**Issue by liudmyla-schastlyvets** [peterh32/react-drag-drop-container#21]
While using DragDropContainer in the modal component I noticed setState warning. Here is its text "Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the t component."
Click on the DragDropContainer adds "mouseup" eventlistener to the whole document which is not removed after unmounting modal component with dnd container.

**Comment by peterh32** [comment]
This should be fixed in release 5.0.0! Thanks.
