### ISSUE TITLE
Not working...?

### ISSUE THREAD

**Issue by ktakeyama12** [peterh32/react-drag-drop-container#31]
Sorry if my question is dumb...I just started learning React a couple days ago.
When I run the code below,
I can drag "Drag me!", but I can not drag it onto "I'm a valid target...".
Also when I load the page, console instantly shows "test", instead of after dragging and dropping "Drag me!"

```
import React from 'react';
import ReactDOM from 'react-dom';
import { DragDropContainer, DropTarget } from 'react-drag-drop-container';

class Game extends React.Component {
    render(){
        return(
            <div className="game">
                 <DragDropContainer targetKey="foo" onDrop={console.log("test")}>
                    <div>Drag Me!</div>
                </DragDropContainer>
                <DropTarget targetKey="foo" >
                    <p>I'm a valid drop target for the object above since we both have the same targetKey!</p>
                </DropTarget>
            </div>
            )
    }
}

ReactDOM.render(
  <Game />,
  document.getElementById('root')
);
```

**Comment by herbertpimentel** [comment]
Your code immediatily shows 'test' because you are invoking a call to console.log on the definition of the component. onDrop must receive a function reference (not a function call) change your code to 
```javascript
onDrop={() => console.log("test")}
```

**Comment by ktakeyama12** [comment]
Thank you very much, it worked!! I need to study more.
